export default {
  incompleteReqInfo: "Information submited is not fully complete",
  unexpectedError: "An unexpected error occurred",
  deletedCollection: "Your collection was deleted successfully",
  errorCreateCollection: "We couldn't create your card collection",
  collectionCreated: "Your collection was created successfully",
  cardAdded: "Card was added to your collection",
  errorAddCard: "We couldn't add your card to the collection",
  errorUpdateCard: "We couldn't update your card",
  unauthorizedMessage: "Invalid credentials",
  expiredToken: "Your session has expired. Please log in again.",
  noToken: "No token was provided",
  invalidToken: "Invalid token",
  errorToken: "An error occurred while validating the token",
  userNotFound: "User was not found",
  collectionNotFound: "Collection was not found",
  passwordChanged: "Your password was changed successfully",
  logoutMessage: "Logged out successfully",
  invalidArguments: "Email/username and password are required",
  usernameAlreadyUsed: "Username already exists, try another one",
  emailAlreadyUsed: "Email already exists, try another one",
  invalidPassword: "Invalid password",
};
